### PR TITLE
Use the concrete5/incremental-filter-branch script

### LINKED ISSUE #2: Delete deleted refs
Let's assume that:
- in day 1 the [main repo](https://github.com/concrete5/concrete5/) contains the branches `A` and `B`:  
  the `splitcore` script correctly pushes those 2 branches to the [final repo](https://github.com/concrete5/concrete5-core).
- in day 2 the main repo contains the branches `A`, and `C`:
  the `splitcore` script correctly pushes those 2 branches to the final repo, but it doesn't delete the remote branch `B` which doesn't exist anymore in the main repo.

For instance, we currently have the `release/8.4.0` branch in the [splitted repo](https://github.com/concrete5/concrete5-core/tree/release/8.4.0) but [not in the main repo](https://github.com/concrete5/concrete5/tree/release/8.4.0).

This can be solved in 2 ways:
1. we never delete branches in the main repo. But @aembler prefers to work directly on the main repo...
2. the `splitcore` deletes the refs that exists in the splitted repo but not in the original repo

### PR DESCRIPTION
**Pull request by mlocati**
Let's switch to the script defined in https://github.com/concrete5/incremental-filter-branch.

This script includes the version of incremental-filter-branch to be used, and automatically downloads.

I did my best to comment any line of this script.

Fix #2

### CODE REVIEW

**Comment by mlocati** [comment]
I also added the `splitcore_logged` command that logs the output of the `splitcore` command.

**Comment by mlocati** [comment]
The [rules specified](https://github.com/concrete5/core_splitter/pull/5/commits/faa31a597489d3d03b24c4800709a540a4f05ce3#diff-fe6943e602bc0132fe6fc1b1196cd564R75) in the `splitcore` currently allow the creation of the `master`, `develop` branches, as well as all the branches that start with `release/`.

Is the inclusion of these `release/` branches correct?

**Comment by KorvinSzanto** [comment]
We want to include all branches, and probably should just pull in the incremental-filter-branch with composer. I'll merge this and get it converted to use composer, what's the best way to include all branches?

**Comment by mlocati** [comment]
> what's the best way to include all branches?

Simply remove this line:
```
--branch-whitelist 'develop master rx:release\/.*' \
```

**Pull request merged**
